name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: '14'
    - name: Build with Maven
      run: |
        mvn clean package
        mvn liberty:create liberty:install-feature liberty:deploy -f decorators/pom.xml
        mvn liberty:create liberty:install-feature liberty:deploy -f interceptors/pom.xml
        mvn liberty:create liberty:install-feature liberty:deploy -f qualifiers/pom.xml
        mvn liberty:create liberty:install-feature liberty:deploy -f scopes/pom.xml
        mvn verify